Repository Ayush7614/Hacktoberfest2021, pull requests merged in 2021-10, with the labels that each got.

#5 Added my name in the Participant list.
  Participants.md
Labels: accepted

#9 Update Participants.md
  Participants.md
Labels: accepted

#10 Updated Participants.md file
  Participants.md
Labels: accepted, hacktoberfest21, hacktoberfest-accepted

#14 update participants file
  Participants.md
Labels: accepted, hacktoberfest21, hacktoberfest-accepted

#15 Update Participants.md
  Participants.md
Labels: accepted, hacktoberfest21, hacktoberfest-accepted

#16 Update Participants.md
  Participants.md
Labels: accepted, hacktoberfest21, hacktoberfest-accepted

#17 Participants.md
  Participants.md
Labels: hacktoberfest21, hacktoberfest-accepted

#21 Update Participants.md
  Participants.md
Labels: accepted, hacktoberfest2021, hacktoberfest-accepted
